conf: layer.conf: Mask firmware-nxp-wifi from meta-imx
The firmware-nxp-wifi_%.bbappend in meta-imx adds packages, which are
already named in the original recipe in meta-freescale, which produces
the following error messages:

    ERROR: firmware-nxp-wifi-1.1-r0 do_package: QA Issue: firmware-nxp-wifi-nxpiw610-sdio is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
    ERROR: firmware-nxp-wifi-1.1-r0 do_package: QA Issue: firmware-nxp-wifi-all-sdio is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
    ERROR: firmware-nxp-wifi-1.1-r0 do_package: QA Issue: firmware-nxp-wifi-all-pcie is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]

Mask the bbappend in meta-imx to workaround this issue, until NXP fixes
this. We do not need the mentioned NXP WiFi firmware in this case
anyway.

Signed-off-by: Martin Schwan <m.schwan@phytec.de>